# initialize
typeset -a precmds

# changing directories
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_SILENT

# completion
setopt ALWAYS_TO_END
setopt LIST_PACKED

setopt NO_AUTO_REMOVE_SLASH

autoload -U compinit
compinit
zstyle ':completion:*' list-colors ''

# history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_NO_FUNCTIONS
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# command
setopt CORRECT
setopt NO_FLOW_CONTROL
setopt PATH_DIRS
setopt RM_STAR_WAIT

# zle
setopt NO_BEEP
setopt BRACE_CCL

bindkey -e
bindkey '\CJ' backward-char
bindkey '\ej' backward-word

# source
local aliase_file=${DOTDIR}/shell/aliases
if [ -f $aliase_file ]; then
  source $aliase_file
fi

local perlbrew=${PERLBREW_ROOT}/etc/bashrc
if [ -f $perlbrew ]; then
  source $perlbrew
fi

# prompt
function echo_prompt {
  prompt='%n@ %30<..<%~$ ';
}
precmds+=echo_prompt

#hook
function precmd {
  for func in $precmds; do
    $func
  done
}

